In [1]:
# !pip install numpy
#Requirement already satisfied:

In [2]:
import numpy as np
import time

In [3]:
#execution time differnece
size = 1_000
py_list = list(range(size))
#print(py_list)

start = time.time()
sq_list = [x**2 for x in py_list]
end =  time.time()
print(f"python list time = {end - start} seconds")

np_arr = np.array(py_list)
#print(np_arr)

start = time.time()
sq_arr = np_arr ** 2
end =  time.time()
print(f"numpy array time = {end - start} seconds")


python list time = 0.00036835670471191406 seconds
numpy array time = 0.0001537799835205078 seconds


In [4]:
#create with built in functions
arr1 = np.zeros((2,3),dtype = "int64")
print(arr1, arr1.shape)

arr1 = np.ones((5,))
print(arr1, arr1.shape)

arr3 = np.full((3,3),100)
print(arr3, arr3.shape)

arr4 = np.eye(3)
print(arr4, arr4.shape)

arr5 = np.arange(0,11,2)
print(arr5, arr5.shape)

arr5 = np.linspace(1,100,4)
print(arr5, arr5.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [7]:
#properties
arr = np.array([[1,2,3],[6,4,5]])
print(arr.shape)

reshaped = arr.reshape((3,2))

print(reshaped, reshaped.shape)
flat = arr.flatten()
print(flat, flat.shape)


(2, 3)
[[1 2]
 [3 6]
 [4 5]] (3, 2)
[1 2 3 6 4 5] (6,)


In [9]:
#Indexing

arr = np.array([[1,2,3],[6,4,5]])
print(arr[1][0])

6


In [11]:
#fancy indexing

arr = np.array([1,2,3,4,5,6])
print(arr.shape)
idx = [0,2,4]
print(arr[idx])

(6,)
[1 3 5]


In [13]:
#boolean indexing

arr = np.array([1,2,3,4,5,6])
print(arr.shape)

print(arr[arr >2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 == 1])

(6,)
[3 4 5 6]
[2 4 6]
[1 3 5]


In [21]:
#slicing
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

print(arr[1:4])
print(arr[:4])
print(arr[1:])
print(arr[:])
print(arr[::2])

(6,)
[2 3 4]
[1 2 3 4]
[2 3 4 5 6]
[1 2 3 4 5 6]
[1 3 5]


In [28]:
#copy in list
nums = [1,5,3,4,5,6]
sub_arr = nums[1:3]
print(sub_arr)
sub_arr[0]=200
print(nums)



[5, 3]
[1, 5, 3, 4, 5, 6]


In [34]:
#view in numpy
arr = np.array([1,2,3,4,5,6])
sub_arr = arr[1:4].copy()
print(sub_arr)

sub_arr[0]=200
sub_arr[2]=2500
print(sub_arr)

print(arr)

[2 3 4]
[ 200    3 2500]
[1 2 3 4 5 6]


In [35]:
# Operations along Axes
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2D)
print(np.sum(arr2D)) #sum of entire array

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

# Slicing
print(arr2D[0:3, 1:3]) #row(0, 1, 2) & col(1, 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2 3]
 [5 6]
 [8 9]]


In [36]:
# 3D array
arr3D = np.array([[[1, 2],[3, 4],[5, 6]], [[7, 8],[9, 10],[11, 12]]])

print(arr3D)
print(arr3D.shape)

#Indexing
print(arr3D[0][1][1])   #4
print(arr3D[1][2][1])   #12

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
4
12
