In [1]:
# !pip install numpy
#Requirement already satisfied:

In [2]:
import numpy as np
import time

In [3]:
#execution time differnece
size = 1_000
py_list = list(range(size))
#print(py_list)

start = time.time()
sq_list = [x**2 for x in py_list]
end =  time.time()
print(f"python list time = {end - start} seconds")

np_arr = np.array(py_list)
#print(np_arr)

start = time.time()
sq_arr = np_arr ** 2
end =  time.time()
print(f"numpy array time = {end - start} seconds")


python list time = 0.0001888275146484375 seconds
numpy array time = 0.00024437904357910156 seconds


In [4]:
#create with built in functions
arr1 = np.zeros((2,3),dtype = "int64")
print(arr1, arr1.shape)

arr1 = np.ones((5,))
print(arr1, arr1.shape)

arr3 = np.full((3,3),100)
print(arr3, arr3.shape)

arr4 = np.eye(3)
print(arr4, arr4.shape)

arr5 = np.arange(0,11,2)
print(arr5, arr5.shape)

arr5 = np.linspace(1,100,4)
print(arr5, arr5.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [5]:
#properties
arr = np.array([[1,2,3],[6,4,5]])
print(arr.shape)

reshaped = arr.reshape((3,2))

print(reshaped, reshaped.shape)
flat = arr.flatten()
print(flat, flat.shape)


(2, 3)
[[1 2]
 [3 6]
 [4 5]] (3, 2)
[1 2 3 6 4 5] (6,)


In [6]:
#Indexing

arr = np.array([[1,2,3],[6,4,5]])
print(arr[1][0])

6


In [7]:
#fancy indexing

arr = np.array([1,2,3,4,5,6])
print(arr.shape)
idx = [0,2,4]
print(arr[idx])

(6,)
[1 3 5]


In [8]:
#boolean indexing

arr = np.array([1,2,3,4,5,6])
print(arr.shape)

print(arr[arr >2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 == 1])

(6,)
[3 4 5 6]
[2 4 6]
[1 3 5]


In [9]:
#slicing
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

print(arr[1:4])
print(arr[:4])
print(arr[1:])
print(arr[:])
print(arr[::2])

(6,)
[2 3 4]
[1 2 3 4]
[2 3 4 5 6]
[1 2 3 4 5 6]
[1 3 5]


In [10]:
#copy in list
nums = [1,5,3,4,5,6]
sub_arr = nums[1:3]
print(sub_arr)
sub_arr[0]=200
print(nums)



[5, 3]
[1, 5, 3, 4, 5, 6]


In [11]:
#view in numpy
arr = np.array([1,2,3,4,5,6])
sub_arr = arr[1:4].copy()
print(sub_arr)

sub_arr[0]=200
sub_arr[2]=2500
print(sub_arr)

print(arr)

[2 3 4]
[ 200    3 2500]
[1 2 3 4 5 6]


In [12]:
# Operations along Axes
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2D)
print(np.sum(arr2D)) #sum of entire array

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

# Slicing
print(arr2D[0:3, 1:3]) #row(0, 1, 2) & col(1, 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2 3]
 [5 6]
 [8 9]]


In [13]:
# 3D array
arr3D = np.array([[[1, 2],[3, 4],[5, 6]], [[7, 8],[9, 10],[11, 12]]])

print(arr3D)
print(arr3D.shape)

#Indexing
print(arr3D[0][1][1])   #4
print(arr3D[1][2][1])   #12

print(arr3D[:, :, 0])        #first col from both layers
print(arr3D[:, 0, :])        #first row from both layers

#Manipulating data
arr3D[:, 0, :] = 99          #change first row to store 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
4
12
[[ 1  3  5]
 [ 7  9 11]]
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [14]:
#Common Data Types
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1.0, 2.0, 3.0])
arr3 = np.array(["hello", "world", "prime", "ai/ml"])

print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

print(arr.nbytes)        # 5 elements * 8 bytes each => 40

new_arr = arr.astype("float64")
print(new_arr, new_arr.dtype)

new_arr = np.array([1, 2, 3, 4, 5], dtype="float64")
print(new_arr, new_arr.dtype)


# Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])
print(arr1, arr1.dtype)
print(arr1 + arr2)
print(arr2 - arr1)

# Objects
arr = np.array(["hello", {1, 2, 3}, 3.14])
print(arr, arr.dtype)


int64
float64
<U5
40
[1. 2. 3. 4. 5.] float64
[1. 2. 3. 4. 5.] float64
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
['hello' {1, 2, 3} 3.14] object


In [15]:
#Vectorization
arr = np.array([1, 2, 3, 4, 5])

sq_arr = arr ** 2       #square of all nums
print(sq_arr)

arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2)      #sum of 2 arrays

[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [16]:
#Broadcasting
arr_mul10 = arr * 10    #multiply by 10 to all nums
print(arr_mul10)

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)

[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]
