In [1]:
# !pip install numpy
#Requirement already satisfied:

In [2]:
import numpy as np
import time

In [3]:
#execution time differnece
size = 1_000
py_list = list(range(size))
#print(py_list)

start = time.time()
sq_list = [x**2 for x in py_list]
end =  time.time()
print(f"python list time = {end - start} seconds")

np_arr = np.array(py_list)
#print(np_arr)

start = time.time()
sq_arr = np_arr ** 2
end =  time.time()
print(f"numpy array time = {end - start} seconds")


python list time = 0.0003581047058105469 seconds
numpy array time = 0.00032067298889160156 seconds


In [4]:
#create with built in functions
arr1 = np.zeros((2,3),dtype = "int64")
print(arr1, arr1.shape)

arr1 = np.ones((5,))
print(arr1, arr1.shape)

arr3 = np.full((3,3),100)
print(arr3, arr3.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)
